project_name: otelcol-custom-test
builds:
  - id: otelcol-custom-test
    goos:
      - linux
    goarch:
      - amd64
    dir: otelcol-custom-test/ocb
    binary: bin/otelcol-custom-test
    ldflags:
      - -s
      - -w
nfpms:
  - id: otelcol-custom-test-rpm
    package_name: otelcol-custom-test
    contents:
      - src: dist/otelcol-custom-test_linux_amd64_v1/bin
        dst: /usr/local/bin/otelcol-custom-test
    scripts:
      preinstall: otelcol-custom-test/scripts/preinstall.sh
      postinstall: otelcol-custom-test/scripts/postinstall.sh
      preremove: otelcol-custom-test/scripts/preremove.sh
    builds:
      - otelcol-custom-test
    formats:
      - rpm
    maintainer: sam wood testing only
    description: otelcol-custom-test
    license: Apache 2.0
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
